### ISSUE TITLE
requirements file missing dependencies

### ISSUE THREAD

**Issue by AvrahamOhana** [C4dynamics/C4dynamics#11]
the requirements.txt file is missing tensorflow.

the error:
ModuleNotFoundError: No module named 'tensorflow'

maybe a conda env yaml file is good solution to make the installation easier

**Comment by C4dynamics** [comment]
you are right. 
tensorflow introduced in the last commit but the requirements file wasn't updated yet.
the yaml is a good solution for conda users. let's give it a shot.

**Comment by AvrahamOhana** [comment]
conda env file added to the repo, closing this issue.
