### ISSUE TITLE
conda env throws an error on OpenCV 

### ISSUE THREAD

**Issue by C4dynamics** [C4dynamics/C4dynamics#14]
ModuleNotFoundError                       Traceback (most recent call last)
...
...
----> 3 import opencv as cv2
      4 from tensorflow import image
      5 from tensorflow.image import combined_non_max_suppression

ModuleNotFoundError: No module named 'opencv'

**Comment by C4dynamics** [comment]
@AvrahamOhana

**Comment by AvrahamOhana** [comment]
the syntax for importing opencv is:
import cv2

the conda env works with open cv:
![image](https://github.com/C4dynamics/C4dynamics/assets/41563341/9027befb-fec1-40d4-af35-465080d2d20f)

**Comment by C4dynamics** [comment]
the error remains even after changing to: import cv2
