### ISSUE TITLE
Git LFS error when trying to clone repository - and a fix

### ISSUE THREAD

**Issue by michaelnaw** [C4dynamics/C4dynamics#33]
Using Ubuntu 23.10, When trying to clone the repository, I got:
<pre><font color="#26A269"><b>michael@michael-desktop</b></font>:<font color="#12488B"><b>~/workspace</b></font>$ git clone https://github.com/C4dynamics/C4dynamics.git
Cloning into &apos;C4dynamics&apos;...
remote: Enumerating objects: 2620, done.
remote: Counting objects: 100% (212/212), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 2620 (delta 129), reused 104 (delta 68), pack-reused 2408
Receiving objects: 100% (2620/2620), 146.37 MiB | 8.62 MiB/s, done.
Resolving deltas: 100% (1583/1583), done.
git-lfs filter-process: 1: git-lfs: not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with &apos;git status&apos;
and retry with &apos;git restore --source=HEAD :/&apos;</pre>

Probably due to the _yolov3.weights_ (248 MB)
The fix in Ubuntu is straightforward. Simply delete the half cloned folder, and:
<pre>sudo apt-get install git-lfs
git lfs install</pre>
(This command needs to be run once per user account)

**Comment by C4dynamics** [comment]
Yes. I can't check it on my windows machine because it has already git lfs installed, but from this [question](https://stackoverflow.com/questions/48392440/git-lfs-clone-vs-git-clone) and references there it seems to occur also on windows. 

Good work. 
I'll add a note in the readme.

**Comment by C4dynamics** [comment]
Just encountered [this one](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-git-lfs-objects-in-archives-of-your-repository), so I enabled the large files to be included in the archives. 
I guess it works also for unix-based. 
Re-open if persists.
