### ISSUE TITLE
PN its not path_planning but guidance...

### ISSUE THREAD

**Issue by AlexPianin** [C4dynamics/C4dynamics#8]

**Comment by C4dynamics** [comment]
you right. 
do you think it's better to open a new module for guidance?

**Comment by C4dynamics** [comment]
the repo provides tools to develop algorithms such as datapoints and sensors. the users develop the algo themselves. 
removed to the examples folder as it is an algorithm.

**Comment by C4dynamics** [comment]
the repo provides tools to develop algorithms such as datapoints and sensors. the users develop the algo themselves.
removed to the examples folder as it is an algorithm.
